// lib/universities.ts

export const UNIVERSITAS_INDONESIA: string[] = [
  // Universitas (PTN)
  "Universitas Indonesia (UI)",
  "Universitas Gadjah Mada (UGM)",
  "Institut Teknologi Bandung (ITB)",
  "Institut Pertanian Bogor (IPB)",
  "Universitas Airlangga (UNAIR)",
  "Universitas Diponegoro (UNDIP)",
  "Universitas Brawijaya (UB)",
  "Universitas Padjadjaran (UNPAD)",
  "Universitas Sebelas Maret (UNS)",
  "Universitas Hasanuddin (UNHAS)",
  "Institut Teknologi Sepuluh Nopember (ITS)",
  "Universitas Andalas (UNAND)",
  "Universitas Sumatera Utara (USU)",
  "Universitas Udayana (UNUD)",
  "Universitas Negeri Jakarta (UNJ)",
  "Universitas Negeri Yogyakarta (UNY)",
  "Universitas Negeri Semarang (UNNES)",
  "Universitas Negeri Malang (UM)",
  "Universitas Negeri Surabaya (UNESA)",
  "Universitas Negeri Padang (UNP)",
  "Universitas Negeri Makassar (UNM)",
  "Universitas Negeri Medan (UNIMED)",
  "Universitas Mulawarman (UNMUL)",
  "Universitas Lambung Mangkurat (ULM)",
  "Universitas Tanjungpura (UNTAN)",
  "Universitas Sam Ratulangi (UNSRAT)",
  "Universitas Sriwijaya (UNSRI)",
  "Universitas Lampung (UNILA)",
  "Universitas Riau (UNRI)",
  "Universitas Jambi (UNJA)",
  "Universitas Bengkulu (UNIB)",
  "Universitas Syiah Kuala (USK)",
  "Universitas Malikussaleh (UNIMAL)",
  "Universitas Borneo Tarakan (UBT)",
  "Universitas Palangka Raya (UPR)",
  "Universitas Halu Oleo (UHO)",
  "Universitas Tadulako (UNTAD)",
  "Universitas Pattimura (UNPATTI)",
  "Universitas Cenderawasih (UNCEN)",
  "Universitas Musamus Merauke (UNMUS)",
  "Universitas Nusa Cendana (UNDANA)",
  "Universitas Mataram (UNRAM)",
  "Universitas Jenderal Soedirman (UNSOED)",
  "Universitas Tidar (UNTIDAR)",
  "Universitas Sultan Ageng Tirtayasa (UNTIRTA)",
  "Universitas Siliwangi (UNSIL)",
  "Universitas Singaperbangsa Karawang (UNSIKA)",
  "Universitas Trunojoyo Madura (UTM)",
  "Universitas Pembangunan Nasional Veteran Jawa Timur",
  "Universitas Pembangunan Nasional Veteran Yogyakarta",
  "Universitas Pembangunan Nasional Veteran Jakarta",
  "Universitas Islam Negeri Syarif Hidayatullah Jakarta (UIN Jakarta)",
  "Universitas Islam Negeri Sunan Kalijaga Yogyakarta (UIN Suka)",
  "Universitas Islam Negeri Maulana Malik Ibrahim Malang (UIN Malang)",
  "Universitas Islam Negeri Sunan Ampel Surabaya (UIN Surabaya)",
  "Universitas Islam Negeri Alauddin Makassar (UIN Makassar)",
  "Universitas Islam Negeri Walisongo Semarang (UIN Walisongo)",
  "Universitas Islam Negeri Sunan Gunung Djati Bandung (UIN Bandung)",
  "Universitas Islam Negeri Ar-Raniry Banda Aceh (UIN Ar-Raniry)",
  "Universitas Islam Negeri Raden Fatah Palembang (UIN Palembang)",
  "Universitas Islam Negeri Sultan Syarif Kasim Riau (UIN Riau)",
  "Universitas Islam Negeri Mataram (UIN Mataram)",
  // PTS
  "Universitas Bina Nusantara (BINUS)",
  "Universitas Telkom (Tel-U)",
  "Universitas Mercu Buana",
  "Universitas Gunadarma",
  "Universitas Trisakti",
  "Universitas Atma Jaya Jakarta",
  "Universitas Atma Jaya Yogyakarta",
  "Universitas Multimedia Nusantara (UMN)",
  "Universitas Pelita Harapan (UPH)",
  "Universitas Katolik Parahyangan (UNPAR)",
  "Universitas Katolik Indonesia Atma Jaya",
  "Universitas Tarumanagara (UNTAR)",
  "Universitas Kristen Indonesia (UKI)",
  "Universitas Kristen Satya Wacana (UKSW)",
  "Universitas Dian Nuswantoro (UDINUS)",
  "Universitas Stikubank (UNISBANK)",
  "Universitas Islam Indonesia (UII)",
  "Universitas Muhammadiyah Yogyakarta (UMY)",
  "Universitas Muhammadiyah Surakarta (UMS)",
  "Universitas Muhammadiyah Malang (UMM)",
  "Universitas Muhammadiyah Surabaya (UM Surabaya)",
  "Universitas Muhammadiyah Jakarta (UMJ)",
  "Universitas Ahmad Dahlan (UAD)",
  "Universitas Amikom Yogyakarta",
  "Universitas Esa Unggul",
  "Universitas Ciputra Surabaya",
  "Universitas Prasetiya Mulya",
  "Universitas Pertamina",
  "Institut Teknologi PLN",
  "Universitas Bakrie",
  "Universitas Nasional (UNAS)",
  "Universitas 17 Agustus 1945 Jakarta (UTA45)",
  "Universitas Bhayangkara Jakarta Raya (UBHARA)",
  "Universitas Pancasila",
  "Universitas Komputer Indonesia (UNIKOM)",
  "Universitas Langlangbuana (UNLA)",
  "Universitas Pasundan (UNPAS)",
  "Universitas Islam Bandung (UNISBA)",
  "Universitas Widyatama (UTama)",
  "Universitas Kristen Maranatha",
  "Universitas Ma Chung",
  "Universitas Surabaya (UBAYA)",
  "Universitas Widya Mandala Surabaya",
  "Universitas Wijaya Kusuma Surabaya",
  "Universitas Narotama Surabaya",
  "Universitas Dinamika (UNDIKA)",
  "Universitas Islam Malang (UNISMA)",
  "Universitas Kanjuruhan Malang (UNIKAMA)",
  "Universitas Teknologi Yogyakarta (UTY)",
  "Universitas Sanata Dharma Yogyakarta (USD)",
  "Universitas Sarjanawiyata Tamansiswa (UST)",
  "Universitas PGRI Yogyakarta (UPY)",
  "Universitas Budi Luhur",
  "Universitas YARSI",
  "Universitas Ibnu Khaldun Bogor (UIKA)",
  "Universitas Ibn Khaldun Jakarta",
  "STMIK Amikom Purwokerto",
  // Politeknik Negeri
  "Politeknik Negeri Jakarta (PNJ)",
  "Politeknik Negeri Bandung (POLBAN)",
  "Politeknik Negeri Semarang (POLINES)",
  "Politeknik Negeri Surabaya (PENS)",
  "Politeknik Negeri Malang (POLINEMA)",
  "Politeknik Negeri Medan (POLMED)",
  "Politeknik Negeri Ujung Pandang (PNUP)",
  "Politeknik Negeri Padang (PNP)",
  "Politeknik Negeri Samarinda (POLNES)",
  "Politeknik Negeri Pontianak (POLNEP)",
  "Politeknik Negeri Lampung (POLINELA)",
  "Politeknik Negeri Jember (POLIJE)",
  "Politeknik Negeri Bali (PNB)",
  "Politeknik Negeri Kupang (PNK)",
  "Politeknik Negeri Ambon (PNA)",
  "Politeknik Elektronika Negeri Surabaya (PENS)",
  "Politeknik Manufaktur Bandung (POLMAN)",
  "Politeknik Perkapalan Negeri Surabaya (PPNS)",
  "Politeknik Energi dan Mineral Akamigas",
  // Institut
  "Institut Bisnis dan Informatika Kesatuan (IBIK)",
  "Institut Seni Indonesia Yogyakarta (ISI Yogyakarta)",
  "Institut Seni Indonesia Surakarta (ISI Surakarta)",
  "Institut Seni Indonesia Denpasar (ISI Denpasar)",
  "Institut Seni Budaya Indonesia (ISBI)",
  "Sekolah Tinggi Akuntansi Negara (STAN)",
  "Sekolah Tinggi Ilmu Statistik (STIS)",
  "Institut Pemerintahan Dalam Negeri (IPDN)",
  "Akademi Ilmu Pengetahuan Indonesia (AIPI)",
];

export function searchUniversitas(query: string, limit = 10): string[] {
  if (!query || query.trim().length < 2) return [];
  const q = query.toLowerCase().trim();
  return UNIVERSITAS_INDONESIA.filter((u) =>
    u.toLowerCase().includes(q)
  ).slice(0, limit);
}
